### ISSUE TITLE
When would the implementation be completed?

### ISSUE THREAD

**Issue by villie17** [drmaj/UnDeepVO#3]
Hi,

Thanks for implementing UnDeepVO. Any time frame on when it would be completed?

Thanks

**Comment by ghost** [comment]
Unfortunately, I've paused working on the exact implementation of the project. The original paper lacks sufficient details to replicate it (a common problem in AI/ML research). I've moved on to other projects. However, the core of the depth estimation framework seems to be taken from this paper/project: https://github.com/mrharicot/monodepth
